### ISSUE TITLE
error from  ‘zingeR-DESeq2’ section? 

### ISSUE THREAD

**Issue by euk020** [statOmics/zingeR#1]
I have "Error: length(df) == 1 is not TRUE" after dse = nbinomWaldTest(dse, betaPrior=TRUE, useT=TRUE, df=rowSums(weights)-2). 
Could you help with this? 
Thank you very much!

**Comment by mikelove** [comment]
zingeR requires the development branch of DESeq2, as I had to make some changes for Koen's package

here was the change I made 9 weeks ago:

```
> git diff d8bbb1f 6a05b3b
...
-Version: 1.17.5
+Version: 1.17.6
...
-    stopifnot(length(df)==1)
+    stopifnot(length(df)==1 | length(df)==nrow(object))
...
```

**Comment by euk020** [comment]
The most updated version of DESea2 solved this problem. Thank you for your help.
