### ISSUE TITLE
Parallel computation

### ISSUE THREAD

**Issue by Vivianstats** [statOmics/zingeR#3]
Is it possible to run the DE analysis using multiple cores?

**Comment by koenvandenberge** [comment]
Dear Vivian,

Unfortunately we have not implemented an option for parallelisation in zingeR.

Best,
Koen

**Comment by koenvandenberge** [comment]
Dear @Vivianstats 

I would also like to mention that if zingeR is too slow for your purposes, you may consider using ZINB-WaVE to estimate the weights, as described here: https://genomebiology.biomedcentral.com/articles/10.1186/s13059-018-1406-4

If interested in combining ZINB-WaVE with DESeq2, @mikelove has written a nice tutorial which you can find here: https://github.com/mikelove/zinbwave-deseq2/blob/master/zinbwave-deseq2.knit.md

Let us know if you'd encounter any further issues.
Best,
Koen
